---
- name: configure webserver with nginx
  hosts: den-web
  become: True
  vars:
    server_name: localhost
    root_dir: /home/den/den/app/web/public
    conf_file: /etc/nginx/sites-available/default
  tasks:
    - name: install certbot-auto
      get_url:
        url: https://dl.eff.org/certbot-auto
        dest: /usr/bin/certbot-auto
        mode: 0700
    - name: get SSL certificate
      shell: |
        certbot-auto certonly --standalone -d den.uma-b.com -m p@uenoryo.com --agree-tos -n
    - name: install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
